#!/usr/bin/env python3
"""Validate or deliberately generate persona-native Claude and Codex adapters."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import tomllib
from pathlib import Path

VERSION = "6.0.0"
MARKER = "# Generated by Personas persona-native-sync.py"
SENSITIVE = re.compile(r"(?:api[_-]?key|token|secret|password|authorization|cookie)", re.I)
LITERAL = re.compile(r"(?:sk-[A-Za-z0-9_-]{12,}|eyJ[A-Za-z0-9_-]{12,}|gh[pousr]_[A-Za-z0-9_-]{12,})")

def fail(message: str) -> None:
    raise ValueError(message)

def persona_data(persona: Path) -> tuple[str, str, str, str]:
    agents = (persona / "AGENTS.md").resolve()
    if not agents.is_file(): fail(f"missing {agents}")
    lines = agents.read_text(encoding="utf-8").splitlines()
    heading = next((line[2:].strip() for line in lines if line.startswith("# ")), None)
    quote = next((line[1:].strip() for line in lines if line.startswith(">")), None)
    if not heading or not quote: fail("AGENTS.md needs an H1 and opening blockquote")
    slug = re.sub(r"[^a-z0-9]+", "-", persona.name.lower()).strip("-")
    if not slug: fail("persona directory does not produce a slug")
    digest = hashlib.sha256(agents.read_bytes()).hexdigest()
    return slug, heading, quote, digest

def credential_free(value: object, key: str = "") -> None:
    if SENSITIVE.search(key):
        if isinstance(value, str) and re.fullmatch(r"\$\{[A-Za-z_][A-Za-z0-9_]*\}", value): return
        fail(f"credential literal is unsupported: {key}")
    if isinstance(value, str) and LITERAL.search(value): fail("credential literal is unsupported")
    if isinstance(value, dict):
        for nested_key, nested in value.items(): credential_free(nested, str(nested_key))
    elif isinstance(value, list):
        for nested in value: credential_free(nested, key)

def load_mcps(persona: Path) -> dict[str, dict[str, object]]:
    source = persona / ".mcp.json"
    if not source.exists(): return {}
    payload = json.loads(source.read_text(encoding="utf-8"))
    if set(payload) - {"mcpServers", "mcp_servers"}:
        fail(".mcp.json has unsupported top-level fields")
    servers = payload.get("mcpServers", payload.get("mcp_servers"))
    if not isinstance(servers, dict): fail(".mcp.json needs an mcpServers object")
    result: dict[str, dict[str, object]] = {}
    for name, raw in servers.items():
        if not isinstance(raw, dict): fail(f"MCP {name} must be an object")
        credential_free(raw)
        kind = raw.get("type", "stdio")
        allowed = {"command", "args", "env", "type"} if kind == "stdio" else {"type", "url"}
        extra = set(raw) - allowed
        if extra: fail(f"MCP {name} has unsupported fields: {', '.join(sorted(extra))}")
        if kind == "stdio":
            if not isinstance(raw.get("command"), str): fail(f"MCP {name} needs a command")
            if "args" in raw and not (isinstance(raw["args"], list) and all(isinstance(x, str) for x in raw["args"])): fail(f"MCP {name} args must be strings")
            if "env" in raw and not isinstance(raw["env"], dict): fail(f"MCP {name} env must be an object")
        elif kind in {"streamable-http", "http"}:
            if not isinstance(raw.get("url"), str) or not raw["url"].startswith(("https://", "http://")): fail(f"MCP {name} needs an HTTP url")
        else: fail(f"MCP {name} transport {kind!r} is unsupported")
        result[str(name)] = raw
    return result

def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)
def codex_mcp(mcps: dict[str, dict[str, object]]) -> str:
    blocks = []
    for name, item in mcps.items():
        lines = [f"[mcp_servers.{name}]"]
        if item.get("type", "stdio") == "stdio":
            lines.append(f"command = {toml_string(item['command'])}")
            if item.get("args"): lines.append("args = [" + ", ".join(toml_string(x) for x in item["args"]) + "]")
            if item.get("env"):
                lines.append("env = {" + ", ".join(f"{k} = {toml_string(v)}" for k, v in item["env"].items()) + "}")
        else:
            lines.append(f"url = {toml_string(item['url'])}")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)

def rendered(slug: str, name: str, description: str, agents: Path, digest: str, mcps: dict[str, dict[str, object]]) -> tuple[str, str, str | None]:
    meta = f"{MARKER}\n# version: {VERSION}\n# input-sha256: {digest}\n"
    claude = f"---\nname: {slug}\ndescription: {description}\n---\n\n{meta}\nRead and follow {agents}.\n"
    mcp = codex_mcp(mcps)
    codex = f"{meta}name = {toml_string(slug)}\ndescription = {toml_string(description)}\ndeveloper_instructions = {toml_string(f'Read and follow {agents}.')}\n"
    if mcp:
        codex += f"\n{mcp}\n"
    config = f"{meta}\n{mcp}\n"
    return claude, codex, config

def safe_write(path: Path, content: str, apply: bool) -> str:
    if path.exists() and not path.read_text(encoding="utf-8").startswith(MARKER) and MARKER not in path.read_text(encoding="utf-8")[:300]:
        fail(f"refusing to overwrite unmarked or other-source file: {path}")
    if path.exists() and path.read_text(encoding="utf-8") == content: return f"current {path}"
    if not apply: return f"drift {path}"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return f"updated {path}"

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--persona", required=True, type=Path)
    parser.add_argument("--runtime", choices=("claude", "codex", "all"), default="all")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--claude-home", type=Path, default=Path.home() / ".claude")
    parser.add_argument("--codex-home", type=Path, default=Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")))
    args = parser.parse_args()
    try:
        persona = args.persona.resolve(); slug, name, description, digest = persona_data(persona); mcps = load_mcps(persona)
        claude, codex, config = rendered(slug, name, description, (persona / "AGENTS.md").resolve(), digest, mcps)
        if args.runtime in ("claude", "all"): print(safe_write(args.claude_home / "agents" / f"{slug}.md", claude, args.apply))
        if args.runtime in ("codex", "all"):
            print(safe_write(args.codex_home / "agents" / f"{slug}.toml", codex, args.apply))
            print(safe_write(args.codex_home / f"persona-{slug}.config.toml", config, args.apply))
        print("Claude path access must permit the live AGENTS.md; global Claude permissions are unchanged.")
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr); return 2
if __name__ == "__main__": raise SystemExit(main())
